name: Build PixelOS for citrus (Android 13 Vanilla)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponces/lineage_buildenv_arm64:latest
    timeout-minutes: 720

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Sync ROM source
        run: |
          export PATH=$HOME/bin:$PATH
          mkdir rom && cd rom
          repo init -u https://github.com/PixelOS-AOSP/manifest -b thirteen --depth=1
          repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all)

      - name: Clone device sources
        run: |
          cd rom
          git clone --depth=1 https://github.com/PixelOS-Devices/device_xiaomi_citrus.git -b thirteen device/xiaomi/citrus
          git clone --depth=1 https://github.com/PixelOS-Devices/vendor_xiaomi_citrus.git -b thirteen vendor/xiaomi/citrus
          git clone --depth=1 https://github.com/PixelOS-Devices/kernel_xiaomi_sm6115.git -b thirteen kernel/xiaomi/sm6115

      - name: Setup build environment
        run: |
          cd rom
          source build/envsetup.sh
          lunch aosp_citrus-userdebug

      - name: Start ROM build
        run: |
          cd rom
          mka bacon -j$(nproc --all)

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: PixelOS-Vanilla-citrus
          path: rom/out/target/product/citrus/*.zip
