name: Build PixelOS for Poco M3 (citrus)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ROM

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install git-core repo python-is-python3 -y

    - name: Initialize ROM source
      run: |
        mkdir rom && cd rom
        repo init -u https://github.com/PixelOS-AOSP/manifest -b fourteen --depth=1

    - name: Sync ROM source
      run: |
        cd rom
        repo sync -c -j8 || repo sync -c -j1

    - name: Clone device trees
      run: |
        cd rom
        git clone https://github.com/PixelOS-Devices/device_xiaomi_citrus.git -b fourteen device/xiaomi/citrus
        git clone https://github.com/PixelOS-Devices/vendor_xiaomi_citrus.git -b fourteen vendor/xiaomi/citrus
        git clone https://github.com/PixelOS-Devices/kernel_xiaomi_citrus.git -b fourteen kernel/xiaomi/citrus
        git clone https://github.com/PixelOS-Devices/device_xiaomi_sm6115-common.git -b fourteen device/xiaomi/sm6115-common || true
        git clone https://github.com/PixelOS-Devices/vendor_xiaomi_sm6115-common.git -b fourteen vendor/xiaomi/sm6115-common || true

    - name: Build ROM
      run: |
        cd rom
        source build/envsetup.sh
        lunch aosp_citrus-userdebug
        mka bacon -j$(nproc --all)

    - name: Upload ROM ZIP
      uses: actions/upload-artifact@v4
      with:
        name: PixelOS-citrus
        path: rom/out/target/product/citrus/*.zip
