name: Build PixelOS for citrus (Android 13 Vanilla)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 720

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev \
          libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3 \
          default-jdk ccache libtinfo5 libncurses5

      - name: Check out the source
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
          git config --global user.name "AjayDash"
          git config --global user.email "ajay@example.com"

      - name: Sync ROM source
        run: |
          mkdir rom && cd rom
          repo init -u https://github.com/PixelOS-AOSP/manifest -b thirteen --depth=1
          repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all)

      - name: Clone device trees
        run: |
          cd rom
          git clone --depth=1 https://github.com/PixelOS-Devices/device_xiaomi_citrus.git -b thirteen device/xiaomi/citrus
          git clone --depth=1 https://github.com/PixelOS-Devices/vendor_xiaomi_citrus.git -b thirteen vendor/xiaomi/citrus
          git clone --depth=1 https://github.com/PixelOS-Devices/kernel_xiaomi_sm6115.git -b thirteen kernel/xiaomi/sm6115

      - name: Build ROM
        run: |
          cd rom
          source build/envsetup.sh
          lunch aosp_citrus-userdebug
          mka bacon -j$(nproc --all)

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: PixelOS-Vanilla-citrus
          path: rom/out/target/product/citrus/*.zip
